<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Filter' => 'Agregar filtro',
    'An unknown error has occurred' => 'Un error desconocido ha ocurrido',
    'False' => 'falso',
    'Loading Please Wait...' => 'Cargando por favor espere...',
    'No filters applied' => 'No hay filtros aplicados',
    'No filters available' => 'No hay filtros disponibles',
    'Parameters' => 'Parámetro',
    'Remove Filter' => 'Remover el Filtro',
    'Run' => 'Ejecutar',
    'True' => 'cierto',
    'You cannot remove this filter, it is required' => 'No se puede remover este filtro, se requiere',
    'after' => 'después',
    'before' => 'antes',
    'between' => 'entre',
    'contains' => 'contiene',
    'ends with' => 'termina con',
    'equal to' => 'igual a',
    'is greater than' => 'es mayor que',
    'is less than' => 'es menos que',
    'is not null' => 'No es nulo',
    'is null' => 'es nulo',
    'is one of' => 'es uno de',
    'not equal to' => 'no es igual a',
    'starts with' => 'comienza con',
    '{comparisonType} is not a valid comparison type for {parameterDisplayName}' => '{comparisonType} no es un tipo de comparación válida para {parameterDisplayName}',
    '{parameterDisplayName} is required' => 'Se requiere {parameterDisplayName}',
    '{value} is not a valid value for {parameterDisplayName}' => '{value} no es un valor válido para {parameterDisplayName}',
];

